### ISSUE TITLE
Update the timeseries parameters

### ISSUE THREAD

**Issue by larjohn** [openbudgets/DAM#10]
@HimmelStein can you update what gets sent to the timeseries algorithm?

It can be found at https://github.com/openbudgets/DAM/blob/staging_indigo/tasks/dam.json

**Comment by wk0206** [comment]
@larjohn @HimmelStein DAM is updated ,
now the input is
`json_data = request.args.get('json_data')`
`time = request.args.get('time')`
`amount = request.args.get('amount')`
`prediction_steps = request.args.get('prediction_steps', '4')`
commit be9b97c51ae63f3151357199c2a4b3504e8ea813

**Comment by wk0206** [comment]
@larjohn @HimmelStein 
I have use the new DAM test for the time series algorithm, but has error returned from the [server](http://okfnrg.math.auth.gr/ocpu/library/OBeU/R/ts.obeu/print).

After get the request from Indigo, DAM will package all data and parameters and send them to the link.

You can check the link and their code, their algorithm only accept 2 parameters that is 'tsdata' and 'prediction_steps', so should we have a look, is that really necessary to add 'amount' and 'time' in the request?  If it really necessary, then we have to ask OKFGR to change their code too.

I will continue working on this, if I have something new, I will inform you.

**Comment by wk0206** [comment]
http://okfnrg.math.auth.gr/ocpu/test/
the test can not continue with such parameters
Most important thing is I don't know what is the acceptable 'tsdata' format.
And with the raw data from ruldorf, it can not go further.

Can you provide us an API document, or an example?
Or as a Greece member, please forward to the one who can help.


> Invalid time series object.
>
>In call:
>ts.obeu(tsdata = "http://apps.openbudgets.eu/api/3/cubes/aragon-2010-income__a9066/facts?pagesize=30", 
>    prediction_steps = 4)

**Comment by larjohn** [comment]
You can POST here:` http://okfnrg.math.auth.gr/ocpu/library/TimeSeries.OBeu/R/open_spending.ts/print`
the following parameters:

```
json_data:'http://apps.openbudgets.eu/api/3/cubes/global/aggregate?drilldown=global__fiscalPeriod__28951.prefLabel&aggregates=global__amount__0397f.sum&pagesize=30'
time:'global__fiscalPeriod__28951.prefLabel'
amount:'global__amount__0397f.sum'
prediction_steps:4
```

**Comment by wk0206** [comment]
I find a tool can do this easily, it will be OK


>@larjohn the parameter is correct, but I find out this is using multipart/form-data method to post the data.
>That make it very difficult to use python to post it.
>[http://docs.python-requests.org/en/latest/user/quickstart/](http://docs.python->requests.org/en/latest/user/quickstart/)
>
>does it possible to change to simple way?
>I will continue check solution, but if you can change to other way to receive the data, it will be great help.

**Comment by wk0206** [comment]
repair is finished , I will ask @hantongliu to update

**Comment by wk0206** [comment]
http://dam-obeu.iais.fraunhofer.de/time_series?amount=global__amount__0397f.sum&json_data=http://apps.openbudgets.eu/api/3/cubes/global/aggregate?drilldown=global__fiscalPeriod__28951.prefLabel%26aggregates=global__amount__0397f.sum%26pagesize=30&time=global__fiscalPeriod__28951.prefLabel&prediction_steps=4

now it is working, please check and close this issue. @larjohn
