### ISSUE TITLE
Staging instructions are missing information

### ISSUE THREAD

**Issue by larjohn** [openbudgets/DAM#2]
It is not possible to install DAM in an Ubuntu VM.

Can you run it in an Ubuntu VM from start to end? There are dependences with wrong names. In addition, the algorithms dependences are required earlier.

**Comment by HimmelStein** [comment]
please check out staging_indigo branch, and follow the instructions there.

**Comment by HimmelStein** [comment]
https://github.com/openbudgets/DAM/tree/staging_indigo

**Comment by larjohn** [comment]
It seems to progress much better now. I am stuck at this:

(env) root@ubuntu:/opt/DAM# python3 manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from app import app, db
  File "/opt/DAM/app.py", line 7, in <module>
    from worker import conn_dm
  File "/opt/DAM/worker.py", line 5, in <module>
    import config
  File "/opt/DAM/config.py", line 5, in <module>
    class Config(object):
  File "/opt/DAM/config.py", line 10, in Config
    SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
  File "/opt/DAM/env/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATABASE_URL'

**Comment by HimmelStein** [comment]
DATABASE_URL is defined in the .env file
so, before typing the command: make dam, type: source .env

**Comment by larjohn** [comment]
Now it does run, although it is not accessible outside the VM. Can you make it run at 0.0.0.0 instead of 127.0.0.1? Is there a config option for that?

**Comment by HimmelStein** [comment]
try: https://coderwall.com/p/yx23qw/access-your-virtualbox-guest-localhost-from-your-host-os

**Comment by larjohn** [comment]
Eventually, I provided --host 0.0.0.0 and it worked. 

Can you document what is written here, into the README.md? Please, also fix the step 0, as it precedes the cloning of the repository, which is impossible.

**Comment by HimmelStein** [comment]
`source .env` is added to `Makefile`.

**Comment by HimmelStein** [comment]
README.md is updated. 
but, do not see the problem at step 0.

**Comment by larjohn** [comment]
> Step 0: Install some tools, database, e.g. git, redis-server

> `$ make step0

If one hasn't cloned the repository yet, what does `make step0` do?

**Comment by HimmelStein** [comment]
the function of `make step0` is to install some libraries on ubuntu system, such as git, python tools.

**Comment by HimmelStein** [comment]
@mlukasch can you install and test the staging_indigo branch at the fraunhofer server?

**Comment by larjohn** [comment]
> the function of make step0 is to install some libraries on ubuntu system, such as git, python tools.

I see, but step0 means nothing to any operating system. step0 is only valid inside the DAM directory, AFTER you have cloned the repository. If you haven't yet cloned the repository, Makefile is not available so you can't do anything like that.

Other than that, one has to install `make ` in a fresh Ubuntu installation to work with this command.

**Comment by HimmelStein** [comment]
ah definitely. updated now.
