### ISSUE TITLE
Implement CORS headers

### ISSUE THREAD

**Issue by larjohn** [openbudgets/DAM#5]
Cross Origin requests should be allowed, in order to use browser based apps with DAM.

I am trying to run indigo locally with DAM as endpoint, and I get this message:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.0.108:5000/cubes/global/algo. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

I can bypass this by installing a plugin in the browser, but this is not the expected behavior.

**Comment by HimmelStein** [comment]
Hi Lazaros,

I add the CORS function to DAM, and push the new DAM to staging_indigo branch at GitHub. 

please test it, and update me.

best,
-tiansi
